# Generated by Django 4.2.9 on 2026-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ãšltima modificaciÃ³n')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='CÃ©dula')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='GÃ©nero')),
                ('nacionalidad', models.CharField(default='Ecuatoriana', max_length=50, verbose_name='Nacionalidad')),
                ('etnia', models.CharField(blank=True, max_length=50, verbose_name='Etnia/Auto-identificaciÃ³n')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/', verbose_name='Foto carnet')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo de sangre')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias conocidas')),
                ('tiene_discapacidad', models.BooleanField(default=False, verbose_name='Tiene discapacidad')),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=100, verbose_name='Tipo de discapacidad')),
                ('porcentaje_discapacidad', models.PositiveIntegerField(blank=True, null=True, verbose_name='% Discapacidad')),
                ('numero_conadis', models.CharField(blank=True, max_length=20, verbose_name='NÂ° CONADIS')),
                ('relacion_representante', models.CharField(default='Padre/Madre', max_length=50, verbose_name='RelaciÃ³n con el estudiante')),
                ('institucion_anterior', models.CharField(blank=True, max_length=200, verbose_name='InstituciÃ³n anterior')),
                ('grado_anterior', models.CharField(blank=True, max_length=50, verbose_name='Ãšltimo grado aprobado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
