# Generated by Django 4.2.9 on 2026-02-23 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='amie_anterior',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código AMIE de la institución anterior'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='anio_anterior',
            field=models.CharField(blank=True, help_text='Ej: 2023-2024', max_length=9, verbose_name='Año lectivo anterior'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ciudad',
            field=models.CharField(blank=True, default='Quito', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección domiciliaria'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True, help_text='Ej: diabetes, asma, epilepsia', verbose_name='Enfermedades crónicas'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='madre_cedula',
            field=models.CharField(blank=True, max_length=13, verbose_name='Cédula de la madre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='madre_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de la madre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='madre_estado_civil',
            field=models.CharField(blank=True, choices=[('', '---'), ('CASADA', 'Casada'), ('DIVORCIADA', 'Divorciada'), ('VIUDA', 'Viuda'), ('UNION_LIBRE', 'Unión libre')], max_length=20, verbose_name='Estado civil de la madre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='madre_instruccion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nivel de instrucción de la madre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='madre_nombres',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombres de la madre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='madre_ocupacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ocupación de la madre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='madre_telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono de la madre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='medicacion_actual',
            field=models.TextField(blank=True, help_text='Medicamentos que toma regularmente', verbose_name='Medicación actual'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='medico_tratante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Médico tratante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='motivo_cambio',
            field=models.TextField(blank=True, verbose_name='Motivo de cambio de institución'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='necesidades_especiales',
            field=models.TextField(blank=True, help_text='Describa los apoyos o adaptaciones requeridas', verbose_name='Necesidades educativas especiales'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='observaciones_generales',
            field=models.TextField(blank=True, help_text='Información adicional relevante para el proceso de matrícula', verbose_name='Observaciones generales'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='padre_cedula',
            field=models.CharField(blank=True, max_length=13, verbose_name='Cédula del padre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='padre_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del padre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='padre_estado_civil',
            field=models.CharField(blank=True, choices=[('', '---'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('VIUDO', 'Viudo'), ('UNION_LIBRE', 'Unión libre')], max_length=20, verbose_name='Estado civil del padre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='padre_instruccion',
            field=models.CharField(blank=True, help_text='Ej: Primaria, Secundaria, Superior, Posgrado', max_length=50, verbose_name='Nivel de instrucción del padre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='padre_nombres',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombres del padre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='padre_ocupacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ocupación del padre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='padre_telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono del padre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='promedio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Promedio final año anterior'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sector',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sector / Barrio'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='seguro_medico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Seguro médico / IESS'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono de emergencia'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='alergias',
            field=models.TextField(blank=True, help_text='Describa las alergias. Deje vacío si no tiene.', verbose_name='Alergias conocidas'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener entre 10 y 13 dígitos.', regex='^\\d{10,13}$')], verbose_name='Cédula de identidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='etnia',
            field=models.CharField(choices=[('MESTIZO', 'Mestizo/a'), ('INDIGENA', 'Indígena'), ('AFROECUATORIANO', 'Afroecuatoriano/a'), ('MONTUBIO', 'Montubio/a'), ('BLANCO', 'Blanco/a'), ('MULATO', 'Mulato/a'), ('OTRO', 'Otro'), ('NO_DECLARA', 'No declara')], default='MESTIZO', max_length=20, verbose_name='Auto-identificación étnica'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/%Y/', verbose_name='Foto carnet'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Prefiero no decir')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grado_anterior',
            field=models.CharField(blank=True, max_length=50, verbose_name='Último grado/año aprobado'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='institucion_anterior',
            field=models.CharField(blank=True, max_length=200, verbose_name='Institución educativa anterior'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nacionalidad',
            field=models.CharField(default='Ecuatoriana', max_length=60, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numero_conadis',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de carnet CONADIS'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='porcentaje_discapacidad',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de discapacidad (%)'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='relacion_representante',
            field=models.CharField(default='Padre/Madre', help_text='Ej: Padre, Madre, Abuelo/a, Tío/a, Hermano/a', max_length=50, verbose_name='Relación con el estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_discapacidad',
            field=models.CharField(blank=True, help_text='Ej: visual, auditiva, motriz, intelectual', max_length=100, verbose_name='Tipo de discapacidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('', 'Desconocido')], max_length=3, verbose_name='Tipo de sangre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['cedula'], name='estudiantes_cedula_4e5cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['apellidos', 'nombres'], name='estudiantes_apellid_9a83e8_idx'),
        ),
    ]
