# Generated by Django 4.2.9 on 2026-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ãšltima modificaciÃ³n')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.CharField(choices=[('INFO', 'InformaciÃ³n'), ('EXITO', 'Ã‰xito'), ('ADVERTENCIA', 'Advertencia'), ('ERROR', 'Error')], default='INFO', max_length=15)),
                ('titulo', models.CharField(max_length=200, verbose_name='TÃ\xadtulo')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='LeÃ\xadda')),
                ('url_accion', models.CharField(blank=True, max_length=200, verbose_name='URL de acciÃ³n')),
            ],
            options={
                'verbose_name': 'NotificaciÃ³n',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
