# Generated by Django 4.2.9 on 2026-02-23 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0003_alter_historialmatricula_options_and_more'),
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('evento', models.CharField(choices=[('SOLICITUD_RECIBIDA', 'Solicitud de matrícula recibida'), ('EN_REVISION', 'Matrícula en revisión'), ('APROBADA', 'Matrícula aprobada'), ('RECHAZADA', 'Matrícula rechazada'), ('DOC_RECHAZADO', 'Documento rechazado'), ('ANULADA', 'Matrícula anulada')], max_length=30, unique=True, verbose_name='Evento')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto del email')),
                ('cuerpo_html', models.TextField(help_text='Variables disponibles: {{ nombre_representante }}, {{ nombre_estudiante }}, {{ codigo_matricula }}, {{ estado_matricula }}, {{ motivo }}, {{ nombre_institucion }}', verbose_name='Cuerpo en HTML')),
                ('cuerpo_texto', models.TextField(blank=True, help_text='Versión sin HTML para clientes de email básicos', verbose_name='Cuerpo en texto plano')),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Email',
            },
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='email_enviado',
            field=models.BooleanField(default=False, verbose_name='Email enviado'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío del email'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='generada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Generada por (usuario del sistema)'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='matriculas.matricula', verbose_name='Matrícula relacionada'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='texto_boton',
            field=models.CharField(blank=True, default='Ver detalle', max_length=50, verbose_name='Texto del botón de acción'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False, verbose_name='Leída'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('INFO', 'Información'), ('EXITO', 'Éxito'), ('ADVERTENCIA', 'Advertencia'), ('ERROR', 'Error')], default='INFO', max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='url_accion',
            field=models.CharField(blank=True, help_text='Enlace al detalle de la matrícula o documento', max_length=300, verbose_name='URL de acción'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['destinatario', 'leida'], name='notificacio_destina_103707_idx'),
        ),
    ]
