# Generated by Django 4.2.9 on 2026-02-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ãšltima modificaciÃ³n')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del nivel')),
                ('orden', models.PositiveIntegerField(verbose_name='Orden de visualizaciÃ³n')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ãšltima modificaciÃ³n')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del perÃ\xadodo')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio de clases')),
                ('fecha_fin', models.DateField(verbose_name='Fin de clases')),
                ('fecha_inicio_matriculas', models.DateField(verbose_name='Inicio matrÃ\xadculas')),
                ('fecha_fin_matriculas', models.DateField(verbose_name='Fin matrÃ\xadculas')),
                ('es_activo', models.BooleanField(default=False, verbose_name='PerÃ\xadodo activo')),
            ],
            options={
                'verbose_name': 'PerÃ\xadodo AcadÃ©mico',
                'verbose_name_plural': 'PerÃ\xadodos AcadÃ©micos',
            },
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ãšltima modificaciÃ³n')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=10, verbose_name='Paralelo (A, B, C...)')),
                ('cupo_maximo', models.PositiveIntegerField(default=35, verbose_name='Cupo mÃ¡ximo')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='periodos.nivel')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='periodos.periodoacademico')),
            ],
            options={
                'verbose_name': 'Paralelo',
                'verbose_name_plural': 'Paralelos',
                'ordering': ['nivel__orden', 'nombre'],
                'unique_together': {('periodo', 'nivel', 'nombre')},
            },
        ),
    ]
