# Generated by Django 4.2.9 on 2026-02-23 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodoacademico',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Período Académico', 'verbose_name_plural': 'Períodos Académicos'},
        ),
        migrations.AddField(
            model_name='nivel',
            name='subnivel',
            field=models.CharField(choices=[('PREPARATORIA', 'Preparatoria (1ro EGB)'), ('BASICA_ELEMENTAL', 'Básica Elemental (2do-4to EGB)'), ('BASICA_MEDIA', 'Básica Media (5to-7mo EGB)'), ('BASICA_SUPERIOR', 'Básica Superior (8vo-10mo EGB)'), ('BGU', 'Bachillerato General Unificado (BGU)')], default='BASICA_ELEMENTAL', max_length=20, verbose_name='Sub-nivel educativo'),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='jornada',
            field=models.CharField(choices=[('MATUTINA', 'Matutina'), ('VESPERTINA', 'Vespertina'), ('NOCTURNA', 'Nocturna')], default='MATUTINA', max_length=20, verbose_name='Jornada'),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='fecha_fin_extra',
            field=models.DateField(blank=True, null=True, verbose_name='Fin matrículas extraordinarias'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='fecha_inicio_extra',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio matrículas extraordinarias'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='permite_matricula_extra',
            field=models.BooleanField(default=False, verbose_name='Permite matrícula extraordinaria'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='regimen',
            field=models.CharField(choices=[('SIERRA', 'Sierra'), ('COSTA', 'Costa / Galápagos')], default='SIERRA', max_length=10, verbose_name='Régimen'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción adicional'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='nombre',
            field=models.CharField(help_text='Ej: 1ro EGB, 8vo EGB, 2do BGU', max_length=100, verbose_name='Nombre del nivel'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='orden',
            field=models.PositiveIntegerField(help_text='1 para primero, 13 para 3ro BGU', verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=35, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Cupo máximo de estudiantes'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='periodos.nivel', verbose_name='Nivel / Grado'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='nombre',
            field=models.CharField(help_text='Ej: A, B, C', max_length=5, verbose_name='Identificador del paralelo'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='periodos.periodoacademico', verbose_name='Período académico'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='es_activo',
            field=models.BooleanField(default=False, help_text='Solo un período puede estar activo a la vez', verbose_name='Período activo'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fin del año lectivo'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='fecha_fin_matriculas',
            field=models.DateField(verbose_name='Fin de matrículas'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='fecha_inicio_matriculas',
            field=models.DateField(verbose_name='Inicio de matrículas'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='nombre',
            field=models.CharField(help_text='Ej: 2024-2025 Sierra', max_length=100, unique=True, verbose_name='Nombre del período'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
    ]
