# Generated by Django 4.2.9 on 2026-02-23 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sector',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sector / Barrio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_alt',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono alternativo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_expiracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración del token'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=64, verbose_name='Token de verificación de email'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acceso_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP de acceso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener entre 10 y 13 dígitos numéricos.', regex='^\\d{10,13}$')], verbose_name='Cédula / Pasaporte'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección domiciliaria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/%Y/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?[\\d\\s\\-]{7,15}$')], verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador / Dispositivo')),
                ('fecha_login', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('fecha_logout', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('exitosa', models.BooleanField(default=True, verbose_name='Sesión exitosa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de usuario',
                'verbose_name_plural': 'Sesiones de usuarios',
                'ordering': ['-fecha_login'],
            },
        ),
    ]
