# Generated by Django 4.2.9 on 2026-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ãšltima modificaciÃ³n')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('archivo', models.FileField(upload_to='documentos/matriculas/%Y/%m/', verbose_name='Archivo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de verificaciÃ³n'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('observacion', models.TextField(blank=True, verbose_name='ObservaciÃ³n del revisor')),
            ],
            options={
                'verbose_name': 'Documento de MatrÃ\xadcula',
                'verbose_name_plural': 'Documentos de MatrÃ\xadcula',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ãšltima modificaciÃ³n')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del documento')),
                ('descripcion', models.TextField(blank=True, verbose_name='DescripciÃ³n/Instrucciones')),
                ('es_obligatorio', models.BooleanField(default=True, verbose_name='Es obligatorio')),
                ('aplica_primera_vez', models.BooleanField(default=True, verbose_name='Aplica para primera matrÃ\xadcula')),
                ('aplica_renovacion', models.BooleanField(default=False, verbose_name='Aplica para renovaciÃ³n')),
                ('aplica_discapacidad', models.BooleanField(default=False, verbose_name='Aplica para discapacidad')),
                ('formatos_permitidos', models.CharField(default='PDF,JPG,PNG', max_length=100, verbose_name='Formatos permitidos')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['nombre'],
            },
        ),
    ]
