# Generated by Django 4.2.9 on 2026-02-21 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentomatricula',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_verificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
