# Generated by Django 4.2.9 on 2026-02-23 17:59

import apps.documentos.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0003_alter_historialmatricula_options_and_more'),
        ('documentos', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentomatricula',
            options={'ordering': ['tipo__orden'], 'verbose_name': 'Documento de Matrícula', 'verbose_name_plural': 'Documentos de Matrícula'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
        migrations.AddField(
            model_name='documentomatricula',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación'),
        ),
        migrations.AddField(
            model_name='documentomatricula',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre original del archivo'),
        ),
        migrations.AddField(
            model_name='documentomatricula',
            name='tamano_bytes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño en bytes'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='aplica_traslado',
            field=models.BooleanField(default=True, verbose_name='Aplica para traslado'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='codigo',
            field=models.CharField(default='', help_text='Ej: CEDULA_ESTUDIANTE, PARTIDA_NACIMIENTO', max_length=30, unique=True, verbose_name='Código interno'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de presentación'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='tamano_maximo_mb',
            field=models.PositiveIntegerField(default=10, verbose_name='Tamaño máximo (MB)'),
        ),
        migrations.AlterField(
            model_name='documentomatricula',
            name='archivo',
            field=models.FileField(upload_to=apps.documentos.models.ruta_documento, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.documentos.models.validar_tamano_archivo], verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentomatricula',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='documentomatricula',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de verificación'), ('VERIFICADO', 'Verificado y aceptado'), ('RECHAZADO', 'Rechazado — debe volver a subir')], default='PENDIENTE', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='documentomatricula',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='matriculas.matricula', verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='documentomatricula',
            name='observacion',
            field=models.TextField(blank=True, help_text='Visible al representante. Indique por qué se rechazó.', verbose_name='Observación del revisor'),
        ),
        migrations.AlterField(
            model_name='documentomatricula',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='documentomatricula',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AlterField(
            model_name='documentomatricula',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='aplica_discapacidad',
            field=models.BooleanField(default=False, verbose_name='Aplica solo si tiene discapacidad'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='aplica_primera_vez',
            field=models.BooleanField(default=True, verbose_name='Aplica para primera matrícula'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='aplica_renovacion',
            field=models.BooleanField(default=False, verbose_name='Aplica para renovación'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Explique cómo debe presentarse el documento.', verbose_name='Descripción / Instrucciones al representante'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='formatos_permitidos',
            field=models.CharField(default='pdf,jpg,jpeg,png', help_text='Extensiones separadas por coma. Ej: pdf,jpg,png', max_length=100, verbose_name='Formatos permitidos'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del documento'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AlterUniqueTogether(
            name='documentomatricula',
            unique_together={('matricula', 'tipo')},
        ),
    ]
