# Generated by Django 4.2.9 on 2026-02-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodos', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=15)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ãšltima modificaciÃ³n')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='CÃ³digo de matrÃ\xadcula')),
                ('tipo', models.CharField(choices=[('NUEVA', 'Primera matrÃ\xadcula'), ('RENOVACION', 'RenovaciÃ³n')], default='NUEVA', max_length=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisiÃ³n'), ('EN_REVISION', 'En revisiÃ³n'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('motivo_rechazo', models.TextField(blank=True, verbose_name='Motivo de rechazo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='estudiantes.estudiante')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='periodos.paralelo')),
            ],
            options={
                'verbose_name': 'MatrÃ\xadcula',
                'verbose_name_plural': 'MatrÃ\xadculas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
