# Generated by Django 4.2.9 on 2026-02-23 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estudiantes', '0003_estudiante_amie_anterior_estudiante_anio_anterior_and_more'),
        ('periodos', '0002_alter_periodoacademico_options_nivel_subnivel_and_more'),
        ('matriculas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialmatricula',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de matrícula', 'verbose_name_plural': 'Historial de matrículas'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='fecha_aprobacion',
        ),
        migrations.AddField(
            model_name='matricula',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_anuladas', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación / rechazo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio de revisión'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='matricula_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matricula_siguiente', to='matriculas.matricula', verbose_name='Matrícula del período anterior'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='motivo_anulacion',
            field=models.TextField(blank=True, verbose_name='Motivo de anulación'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='numero_intentos',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de veces rechazada'),
        ),
        migrations.AlterField(
            model_name='historialmatricula',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='historialmatricula',
            name='estado_anterior',
            field=models.CharField(max_length=15, verbose_name='Estado anterior'),
        ),
        migrations.AlterField(
            model_name='historialmatricula',
            name='estado_nuevo',
            field=models.CharField(max_length=15, verbose_name='Estado nuevo'),
        ),
        migrations.AlterField(
            model_name='historialmatricula',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio'),
        ),
        migrations.AlterField(
            model_name='historialmatricula',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='codigo',
            field=models.CharField(help_text='Generado automáticamente', max_length=20, unique=True, verbose_name='Código de matrícula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada - Requiere correcciones'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='estudiantes.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Visible al representante. Explique qué debe corregir.', verbose_name='Motivo de rechazo'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas del personal (no visible al representante)', verbose_name='Observaciones internas'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='periodos.paralelo', verbose_name='Paralelo asignado'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Representante solicitante'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo',
            field=models.CharField(choices=[('NUEVA', 'Primera matrícula'), ('RENOVACION', 'Renovación de matrícula'), ('TRASLADO_ENTRADA', 'Traslado desde otra institución')], default='NUEVA', max_length=20, verbose_name='Tipo de matrícula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['codigo'], name='matriculas__codigo_649db9_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['estado'], name='matriculas__estado_e1f32e_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['estudiante', 'paralelo'], name='matriculas__estudia_5c8e7d_idx'),
        ),
    ]
